name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main, prod]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js environment
        uses: actions/setup-node@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: true

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=p3d-web
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
